### ISSUE TITLE
When i use libevent for a client program, when a BEV_EVENT_ERROR or BEV_EVENT_TIMEOUT or other events recevied, why the eventloop will be quit automatically？

### ISSUE THREAD

**Issue by guoxiangCN** [libevent/libevent#1106]
In the event_cb, the BEV_EVENT_CONNECTED can continue the eventloop, and other events will exit the eventloop? Why? i didn't use the bufferevent_free to free it! why this event removed from eventlist?

```c
void client_read_cb(struct bufferevent *bev, void *ctx);
void client_write_cb(struct bufferevent *bev, void *ctx);
void client_event_cb(struct bufferevent *bev, short what, void *ctx);

int main(int argc, char **argv) 
{

#ifdef _WIN32
	WSADATA wsa;
	WSAStartup(MAKEWORD(2,2), &wsa);
#else
	if(signal(SIGPIPE, SIG_IGN) == SIG_ERR)
	{
		std::cerr << "cannot register SIG_IGN handler to signal `SIGPIPE`" << std::endl;
		return EXIT_FAILURE;
	}
#endif
	struct event_base *pBase = event_base_new();
	assert(pBase != nullptr);

	// create a bufferevent 
	struct bufferevent *bev =  bufferevent_socket_new(pBase, -1, BEV_OPT_CLOSE_ON_FREE);
	
	// create a server sockaddr
	struct sockaddr_in servAddr;
	memset(&servAddr, 0, sizeof(servAddr));
	servAddr.sin_family = AF_INET;
	servAddr.sin_port = htons(12306);
	evutil_inet_pton(AF_INET, "127.0.0.1", &servAddr.sin_addr);

	// set bufev callbacks
	bufferevent_setcb(bev, client_read_cb, client_write_cb, client_event_cb, (void *)pBase);

	// enable read write event
	bufferevent_enable(bev, EV_READ | EV_WRITE);

	// set timeout
	struct timeval timeout_read = {100, 0};
	bufferevent_set_timeouts(bev,  &timeout_read, NULL);

	// connect to server
	int ret = bufferevent_socket_connect(bev, (sockaddr *)&servAddr, sizeof(servAddr));
	if(ret == -1)
	{
		// ret == 0 just tell us the method success invoked instead of success connected.
		LOG_ERR("bufferevent_socket_connect error");
		bufferevent_free(bev);
		return -1;
	}

	event_base_dispatch(pBase);
	LOG_INFO("event loop quit....");
	return 0;
}



void client_read_cb(struct bufferevent *bev, void *ctx)
{
	LOG_INFO("client_read_cb");
}

void client_write_cb(struct bufferevent *bev, void *ctx)
{
	LOG_INFO("client_write_cb");
}

void client_event_cb(struct bufferevent *bev, short what, void *ctx)
{
	LOG_INFO("client_event_cb");
	if (what & BEV_EVENT_CONNECTED)
	{
		LOG_INFO("connect success !");
		return;
	}
	 else if(what & BEV_EVENT_ERROR)
	{
		LOG_ERR("error occured");
		// bufferevent_free(bev);
		return;
	}
	else if((what & BEV_EVENT_TIMEOUT) && (what & BEV_EVENT_READING))
	{
		LOG_ERR("reading timeout");
		//bufferevent_free(bev);
		// 会自动退出程序.
		return;
	} 
	// else if(what & BEV_EVENT_EOF)
	// {
	// 	LOG_ERR("BEV_EVENT_EOF, 服务器断开链接!");
	// 	LOG_ERR(what);
	// 	bufferevent_free(bev);
	// 	return;
	// }
	else {
		LOG_INFO("other events" << what);
		//bufferevent_enable(bev, EV_READ | EV_WRITE);
		return;
	}
}
```

**Comment by guoxiangCN** [comment]
Sorry, the code format is bad, I tried to typeset, but the results are not satisfactory~

**Comment by azat** [comment]
>When i use libevent for a client program, when a BEV_EVENT_ERROR or BEV_EVENT_TIMEOUT or other events recevied, why the eventloop will be quit automatically

I guess that you get BEV_EVENT_ERROR during connect, and this will remove readw/rite event, since if it fails then you can't do anything with the bufferevent anyway.

And since there will be no more events in the event_base it will exit, you can use `event_base_loop(base, EVLOOP_NO_EXIT_ON_EMPTY)`

>Sorry, the code format is bad, I tried to typeset, but the results are not satisfactory~

Fixed

**Comment by guoxiangCN** [comment]
> > When i use libevent for a client program, when a BEV_EVENT_ERROR or BEV_EVENT_TIMEOUT or other events recevied, why the eventloop will be quit automatically
> 
> I guess that you get BEV_EVENT_ERROR during connect, and this will remove readw/rite event, since if it fails then you can't do anything with the bufferevent anyway.
> 
> And since there will be no more events in the event_base it will exit, you can use `event_base_loop(base, EVLOOP_NO_EXIT_ON_EMPTY)`
> 
> > Sorry, the code format is bad, I tried to typeset, but the results are not satisfactory~
> 
> Fixed

Thank you for typesetting my code, but I still have some questions to ask you~
When an BEV_EVENT_TIMEOUT event goes ready, the current event seems to be removed from the event list. Is the timeout event removed by libevent's own design, or is the BEV_EVENT_ERROR flag set together when the timeout event occurs?
I am not next to my computer for the time being. I will verify it when I go back 。

**Comment by azat** [comment]
>When an BEV_EVENT_TIMEOUT event goes ready

For read/write/connect?

**Comment by guoxiangCN** [comment]
> > When an BEV_EVENT_TIMEOUT event goes ready
> 
> For read/write/connect?

read timeout. i just print a  log and then return from the callback, the eventloop will exit also.

**Comment by azat** [comment]
>read timeout. i just print a log and then return from the callback, the eventloop will exit also.

You should re-enable EV_READ on timeout, i.e. `bufferevent_enable(bev, EV_READ)`

**Comment by guoxiangCN** [comment]
> > read timeout. i just print a log and then return from the callback, the eventloop will exit also.
> 
> You should re-enable EV_READ on timeout, i.e. `bufferevent_enable(bev, EV_READ)`

ok, thank you, 
I will read the source code of the project again when I have time. since  I may have a deeper understanding
